### ISSUE TITLE
Single tag with ID

### ISSUE THREAD

**Issue by slyandsmart** [MomsFriendlyRobotCompany/moms_apriltag#3]
Is it somehow possible to generate a singe tag with a certain id. 
I tryed:
    span =4
    family = "tag36h11"
    shape = (1,1) 
    scale = 10
    filename = 'id'+str(span)+'.png'
    #make tag board
    tgt = apt.board(shape, family, scale,span)
    imageio.imwrite(filename, tgt)

but it wont work

**Comment by walchko** [comment]
So that wasn't the intent, but it can be done. You just need to trick the generator function into producing an array of 1 image.

``` python
from moms_apriltag.target import generate
import numpy as np

# so below I am getting an array of tags, but really
# my array is only tag number 4. That is why I grab
# index zero of the returned array
tag = generate(family, [4])[0]
print(tag)
im = np.array(tag.array) # so array, contains the image data
```

Now you have a numpy image you can do what you want with. If you want to view it, do:

``` python
from matplotlib import pyplot as plt

plt.imshow(im, cmap="gray")
```
